set(LLVMSnippyGeneratorSources
  Backtrack.cpp
  CallGraphState.cpp
  CFPermutation.cpp
  CFPermutationPass.cpp
  CLBasicBlockPreprocessPass.cpp
  CodeAddrSampler.cpp
  CodeAddrSamplingPass.cpp
  FallThroughsEraserPass.cpp
  FunctionGeneratorPass.cpp
  FPRNaNIdentifier.cpp
  GeneratorContext.cpp
  GeneratorContextPass.cpp
  GenerationLimit.cpp
  GenerationUtils.cpp
  Generation.cpp
  InstructionGeneratorPass.cpp
  Interpreter.cpp
  JumpLengthenerPass.cpp
  Linker.cpp
  IntervalsToVerify.cpp
  LongJumpRelaxatorPass.cpp
  Policy.cpp
  RegisterGenerator.cpp
  RootRegPoolWrapperPass.cpp
  SimRunner.cpp
  SimulatorContextWrapperPass.cpp
  SnippyFunctionMetadata.cpp
  MemoryManager.cpp
  OperandsReinitializationPolicy.cpp
  OperandsReinitializationValueSource.cpp
  SnippyModule.cpp
  TopMemAccSampler.cpp
  RandomMemAccSampler.cpp
  SMCManager.cpp
  SMCSetSizeGlobalsPass.cpp
)

add_llvm_library(LLVMSnippyGenerator
  DISABLE_LLVM_LINK_LLVM_DYLIB
  STATIC
  ${LLVMSnippyGeneratorSources}
  )

target_link_libraries(LLVMSnippyGenerator
  PRIVATE LLVMSnippyTarget
  PUBLIC LLVMSnippyConfig LLVMSnippyGeneratorUtils
  SnippyHeaders
  )
