name: Snippy pre-commit and post-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            runs-on: ubuntu-24.04
          - name: rocky
            runs-on: ubuntu-24.04
            image: rockylinux:8
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.image || '' }}
    defaults:
      run:
        shell: bash
    env:
      BUILD_DIR: "release/build"
      INSTALL_DIR: "release/install"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            cmake
            libunwind
            lld
            llvm
            third-party
      - name: Install required compiler to be sure (Ubuntu)
        if: matrix.name == 'ubuntu'
        run: sudo apt-get update && sudo apt-get install -y clang-14 ninja-build ccache lld cmake && pip install sphinx myst-parser
      - name: Install required compiler to be sure (Rocky)
        if: matrix.name == 'rocky'
        run: |
          dnf install -y epel-release 'dnf-command(config-manager)'
          dnf config-manager --set-enabled powertools || \
          dnf config-manager --set-enabled PowerTools || \
          dnf config-manager --set-enabled crb
          dnf update -y
          dnf install -y clang ninja-build ccache lld cmake tar xz python3 python3-pip
          pip3 install sphinx myst-parser
      - name: Prepare ccache
        id: prepare_ccache
        run: |
          echo "timestamp=$(TZ=UTC date "+%Y-%m-%d-T%H:%M:%S")" >> $GITHUB_OUTPUT
          echo "CCACHE_DIR=$GITHUB_WORKSPACE/.ccache" >> $GITHUB_ENV
      - name: Set up ccache
        uses: actions/cache@v5
        with:
          path: .ccache
          key: ccache-${{ matrix.name }}-${{ github.job }}-${{ steps.prepare_ccache.outputs.timestamp }}
          restore-keys: ccache-${{ matrix.name }}-${{ github.job }}-
      - name: CMake release config
        run: >-
          cmake -S llvm -B "$BUILD_DIR" -G Ninja
          -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          -DLLVM_EXTERNAL_PROJECT_PASSTHROUGH="CMAKE_C_COMPILER_LAUNCHER;CMAKE_CXX_COMPILER_LAUNCHER"
          -DCMAKE_BUILD_TYPE=Release --preset snippy_basic
      - name: CMake release build
        run: cmake --build "$BUILD_DIR" --target llvm-snippy llvm-ie docs-llvm-snippy-man docs-llvm-snippy-latex docs-llvm-snippy-html
      - name: CMake release test
        run: env CTEST_OUTPUT_ON_FAILURE=1 cmake --build "$BUILD_DIR" --target check-llvm-tools-llvm-snippy
      - name: CMake install
        id: install_release
        run: |
          release_os="$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')-${{ matrix.name }}" # Lowercase OS (linux) + "ubuntu/rocky"
          release_arch="$(uname -m)" # Arch (x86_64, aarch64)
          release_basename="snippy-$release_arch-$release_os"
          release_tarball_filename="$release_basename.tar.xz" # snippy-x86_64-linux.tar.xz
          echo "release_basename=$release_basename" >> $GITHUB_OUTPUT
          echo "release_tarball_filename=$release_tarball_filename" >> $GITHUB_OUTPUT

          for component in llvm-snippy llvm-snippy-man-pages; do
            cmake --install "$BUILD_DIR" --prefix "$INSTALL_DIR" --component "$component"
          done

          tar --xz -C "$INSTALL_DIR" -cvf "$release_tarball_filename" .
      - name: Upload binary install artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.install_release.outputs.release_basename }}
          path: ${{ steps.install_release.outputs.release_tarball_filename }}
          compression-level: 0 # Artifact is already compressed
      # Upload docs only on ubuntu
      - name: Upload html docs artifacts
        if: matrix.name == 'ubuntu'
        uses: actions/upload-artifact@v7
        with:
          name: snippy-doc-html
          path: ${{ env.BUILD_DIR }}/tools/llvm-snippy/docs/html
      - name: Upload latex docs artifacts
        if: matrix.name == 'ubuntu'
        uses: actions/upload-artifact@v7
        with:
          name: snippy-doc-latex
          path: ${{ env.BUILD_DIR }}/tools/llvm-snippy/docs/latex
      - name: Upload github pages artifact
        if: (matrix.name == 'ubuntu') && github.event_name == 'push' && github.ref_name == 'main' && (github.repository_owner == 'syntacore' || github.repository_owner == 'LLVM-Snippy')
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ${{ env.BUILD_DIR }}/tools/llvm-snippy/docs/html
      - name: Show ccache statistics
        run: |
          ccache -s
          ccache -z
  deploy-pages:
    needs: [main]
    if: github.event_name == 'push' && github.ref_name == 'main' && (github.repository_owner == 'syntacore' || github.repository_owner == 'LLVM-Snippy')
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: github-pages
      cancel-in-progress: false
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
